#dependent on https://pypi.org/project/python-steam-api/ and https://pypi.org/project/PyYAML/
#getting steam web API key: https://steamcommunity.com/dev/apikey
#ascii character <, >, :, ", /, \, |, ?, * are unusable in windows for default

remove_char:
    - "<"
    - ">"
    - ":"
    - '"'
    - "'"
    - "/"
    - "\\"
    - "|"
    - "?"
    - "*"
    - " "

path: D:\Test
steam_api_key: 00000000000000000000000000000000
